### ISSUE TITLE
brak obrazka w sekcji napoje 

### ISSUE THREAD

**Issue by walkapralkaB** [walkapralkaDev/pizzeriaCDV#5]
Cześć, widzę że nie dodano obrazka w sekcji napoje.

**Comment by walkapralkaDev** [comment]
commit naprawia ten błąd: 47167dfc1d3ed141ee3caec799b3120c5f6e9a2b

**Comment by walkapralkaDev** [comment]
47167dfc1d3ed141ee3caec799b3120c5f6e9a2b fixes #7
